---
- hosts: all
  tasks:
    - name: Download Couchbase deb
      get_url: url=http://packages.couchbase.com/releases/2.2.0/couchbase-server-community_2.2.0_x86_64.deb
                 dest=~/.
    - name: Install Couchbase deb
      command: /usr/bin/dpkg -i ~/couchbase-server-community_2.2.0_x86_64.deb
                 creates=/opt/couchbase