---
- hosts: all
  tasks:
    - name: Install UI apt packages
      apt: pkg=git-core update_cache=yes

    - name: Install Node.js
      shell: wget http://nodejs.org/dist/v0.10.28/node-v0.10.28-linux-x64.tar.gz -O - | tar -C /usr/local --strip-components 1 -xzf -
               creates=/usr/local/bin/node

    - name: Install global Node packages
      npm: name={{ item.n }} global=yes version={{ item.v }}
      with_items:
        - { n: bower, v: 1.3.12 }
        - { n: gulp, v: 3.8.9 }

    - name: Install NPM dependencies
      npm: path=/vagrant

    - name: Install Bower dependencies
      command: /usr/local/bin/bower install --allow-root chdir=/vagrant
      register: bower
      changed_when: bower.stdout != ''

    - name: Install apt-transport-https for Docker
      apt: pkg=apt-transport-https

    - name: Add key for Docker apt repo
      apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=A88D21E9 state=present

    - name: Add Docker repo to apt sources list
      apt_repository: repo='deb https://get.docker.io/ubuntu docker main'
                        state=present

    - name: Install apt packages for Docker
      apt: pkg={{ item }} update_cache=yes
      with_items:
        - lxc-docker-1.1.0
        - python-pip

    - name: Install docker-py
      pip: name=docker-py version=0.3.1

    - name: Build docker image
      docker_image: path=/vagrant name=poleland state=present

    - name: Run local DynamoDB docker image
      docker: image=fitz/dynamodb-local name=dynamodb command='-port 8000'
                ports=8000:8000 state=running

    - name: Add script adding environment variables
      template: src=env_vars.sh.j2 dest=/home/vagrant/env_vars.sh owner=vagrant
                  group=vagrant mode=0700

    - name: Add sourcing for script with environment variables
      lineinfile: dest=/home/vagrant/.profile
                    line='source /home/vagrant/env_vars.sh'
                    insertafter=EOF state=present

    - name: Add sourcing for aliases to use Docker images
      lineinfile: dest=/home/vagrant/.profile
                    line='source /vagrant/provisioning/docker_aliases.sh'
                    insertafter=EOF state=present

    - name: Create tables in DynamoDB
      command: /vagrant/dynamodb-setup/create-tables.js
      register: dynamodb_tables
      changed_when: dynamodb_tables.stdout != ''
      environment:
        AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
        DYNAMO_DB_PREFIX: dev

    - name: Add test data to DynamoDB
      command: /vagrant/dynamodb-setup/add-test-data.js
      register: dynamodb_data
      changed_when: dynamodb_data.stdout != ''
      environment:
        AWS_ACCESS_KEY_ID: '{{ aws_access_key_id }}'
        AWS_SECRET_ACCESS_KEY: '{{ aws_secret_access_key }}'
        DYNAMO_DB_PREFIX: dev

    - name: Get Docker bridge IP address
      shell: ip route | awk '/docker/ { print $NF }'
      register: docker_bridge
      changed_when: False

    - name: Run docker image
      docker: image=poleland name=poleland
                volumes='/vagrant:/usr/src/node'
                ports='80:80'
                env='AWS_ACCESS_KEY_ID={{ aws_access_key_id }},AWS_SECRET_ACCESS_KEY={{ aws_secret_access_key }},DYNAMO_DB_URL=http://{{ docker_bridge.stdout }}:8000,DYNAMO_DB_PREFIX=dev'
                state=running
